# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ha5mO138an-Qeqy7fJA6GP9SIUto--i
"""

pip install pylatex

import numpy as np
import pylatex

def limite(x):
    listafracc =[]
    lista_int = []
    y = np.arange(1,11)
    for i in range(x):
        listafracc.append(('\\frac{}/{10^',i,'}'))
        lista_int.append((1/10**i))
    return listafracc,lista_int

limite(10)